# Generated by Django 5.2.1 on 2025-06-03 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('atendido', 'Atendido'), ('indeferido', 'Indeferido')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='ImagemSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='solicitacoes/imagens/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='solicitacoes.solicitacao')),
            ],
        ),
    ]
