# Generated by Django 5.2.1 on 2025-06-05 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arvores', '0001_initial'),
        ('solicitacoes', '0002_alter_solicitacao_status_imagemsolicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arvores.especiearvore'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('atendido', 'Atendido'), ('indeferido', 'Indeferido')], default='pendente', max_length=20),
        ),
    ]
