# Generated by Django 5.2.1 on 2025-06-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_alter_solicitacao_especie_alter_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='protocolo',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
