# Generated by Django 5.2.1 on 2025-06-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_solicitacao_resposta_publica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'PENDENTE'), ('ATENDIDO', 'ATENDIDO'), ('INDEFERIDO', 'INDEFERIDO')], default='pendente', max_length=20),
        ),
    ]
