# Generated by Django 5.2.1 on 2025-05-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieArvore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_popular', models.CharField(max_length=100)),
                ('nome_cientifico', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('frutifera', 'Frutífera'), ('ornamental', 'Ornamental'), ('nativa', 'Nativa'), ('exotica', 'Exótica')], max_length=100)),
                ('tamanho', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=20)),
            ],
        ),
    ]
